### ISSUE TITLE
use Homebridge instead of myQ bridge

### ISSUE THREAD

**Issue by jussin5150** [hjdhjd/homebridge-myq2#104]
How so we set up using the HOOB homebridge instead of the myQ bridge?

As stated in #2 
A plugin for Homebridge like this one that emulates the capabilities of a myQ HomeKit bridge device.

**Comment by donavanbecker** [comment]
use [homebrige](homebridge.io) instead of HOOBs

**Comment by jussin5150** [comment]
How? Hoobs uses homebridge, correct? I installed the plugin, myq2 but I'm not sure how to set up my garage door.

**Comment by donavanbecker** [comment]
Nope, hoobs has taken homebridge and changed it to their likings. Is your garage door hooked up to wifi?

**Comment by jussin5150** [comment]
It's not. I'm assuming the garage door has to have wifi in order to use homebridge?

**Comment by hjdhjd** [comment]
I think I get your question. If you look on the main plugin page: https://github.com/hjdhjd/homebridge-myq2 you'll see a link to see if your garage door opener is already compatible with myQ: https://www.myq.com/myq-compatibility

If you don't already have a myQ-enabled garage door opener, and a myQ account, this plugin won't be useful to you. You need to first have those prerequisites in place. You can check the above links for more detail, particularly the myQ site.

**Comment by jlg89** [comment]
HOOBS is just a "wrapper" for homebridge, and it simplifies (at least) initial setup, especially if you're new to homebridge. Some folks prefer to use the homebridge-config-ui-x plugin instead of HOOBS, but there's really not that much difference from a usability standpoint. Some folks even eschew fancy point-and-click configuration front ends, but there's 
really not that much difference from a functionality standpoint.

The garage door opener does need to be a supported Chamberlain model, with WiFi. If it has a "myQ" logo on it, it should work. If your opener is a supported model, and there's any chance that you'll ever need to bridge other "smart home" devices to whatever your system may be (HomeKit etc.), then it's almost certainly worth your while to set up a homebridge server instead of using a myQ bridge. You'll end up with a lot more functionality for about the same money.

On the other hand, if you won't need homebridge for anything else but the myQ connectivity, you might be happier with the "official" myQ bridge and the Chamberlain tech support that comes with it.

**Comment by donavanbecker** [comment]
> HOOBS is just a "wrapper" for homebridge, and it simplifies (at least) initial setup, especially if you're new to homebridge. Some folks prefer to use the homebridge-config-ui-x plugin instead of HOOBS, but there's really not that much difference from a usability standpoint. Some folks even eschew fancy point-and-click configuration front ends, but there's
> really not that much difference from a functionality standpoint.

They have changed a lot of code different the homebridge. so plugins can work differently then homebridge itself.

**Comment by hjdhjd** [comment]
@jlg89 There are more than just Chamberlain-branded garage door openers that work with myQ. The key is myQ compatibility. Craftsman, Liftmaster, etc...I get these are all brands of the same company, but that's not obvious to everyone.

@donavanbecker Yep...but my understanding is it works fine in HOOBS currently.

Closing this one.
