### ISSUE TITLE
Question about recent releases 1.2.X

### ISSUE THREAD

**Issue by rcoletti116** [hjdhjd/homebridge-myq2#22]
There have been many releases the last few days. I'm curious if there be some general release notes from 1.2+?

Thanks!

**Comment by donavanbecker** [comment]
I would be interested in a changelog too.

**Comment by hjdhjd** [comment]
UI updates and a few minor fixes like dealing with a timeout / resume issue someone called out. New feature about to be added around opener selection / filtering.

The major version bump was because we’re now a verified plugin, primarily.

Next major release will be to focus on implementing the latest MyQ API. They bumped major versions to 5 (and 5.1)...it’s effectively a whole new API to deal with.

Thanks.
